### ISSUE TITLE
build errors in both backend projects

### ISSUE THREAD

**Issue by leopoldHatFertig** [eclipse-basyx/basyx-applications#10]
Hi,
I face several build errors after just cloning the main branch and doing a nuget restore.
Though all packages and dependencies loaded successfully, there remain several errors.
Any idea how to fix this?
Any help appreciated.
![image](https://user-images.githubusercontent.com/49842684/200094404-3a38f2ac-cd25-4d86-ad6d-b8b397c4aa46.png)

**Comment by aaronzi** [comment]
I'm not an expert when it comes to the backend Projects but it seems like something went wrong with the Nuget packages. As far as I can remember you don't have to rebuild any packages. To reproduce your issue I cloned the project in Visual Studio und just hit play for the Registry and AAS Generator. For me it worked right away. Try deleting all Nugets and install them again (Version 1.0.0). Check if .dotnet is installed in the right version. If that not helps, you could also try to run the Basyx Dotnet Examples: https://github.com/eclipse-basyx/basyx-dotnet-examples or the Basyx Java Examples: https://github.com/eclipse-basyx/basyx-java-examples

As long as you start a registry and an AAS, the GUI can visualize that AAS.

Hope this helps :)

**Comment by leopoldHatFertig** [comment]
Thanks for your help.
I finally got it to work by not only clearing all by nuget caches.
I also had to reset my nuget feeds and just re-added nuget.org as source. [https://learn.microsoft.com/en-us/nuget/resources/nuget-faq#i-don-t-see-nuget-org-in-my-list-of-repositories--how-do-i-get-it-back-](url)
Maybe other nuget sources got in the way there.
