### ISSUE TITLE
Could not reach Asset Administration Shell

### ISSUE THREAD

**Issue by Deputy-Chief-Hardy** [eclipse-basyx/basyx-applications#11]
Hi, when using the gui and trying to open an AAS, it doesn't show unfortunately the sumodels. By clicking on the AAS it says "Could not reach Asset Adminstration Shell!" Do you have any idea how to fix this problem? I activated in both context.properties (server and registry) `accessControlAllowOrigin=*` and here is a screenshot:

![Screenshot GUI](https://user-images.githubusercontent.com/49750085/211307699-a1782918-6740-4450-af10-1656e47fd8c7.PNG)

**Comment by aaronzi** [comment]
You are using the docker-compose from the java examples right? It seems like the registry is running (indicated by the two registered AAS on the left) but the Shells themselves are either not running or not reachable. First of all, please check in the Docker dashboard if the Shells are started. If they are started, test if you can reach them by opening the URL of the AAS in the browser (e.g. http://localhost:4001/aas). Hope this helps :)

**Comment by Deputy-Chief-Hardy** [comment]
Hi @aaronzi, 
thanks for your quick answer! I encountered the problem. First of all I needed the latest version of the gui, which is v221024, and afterwards I had to change the port of the server. My port mapping was 8081:4001, which is shown in every tutorial and should also work with a defined registry.hostpath in the aas.properties according to this video https://www.youtube.com/watch?v=CGZEJVNEjoY&list=PLgzHQiUJr6D-4E1nlI_nOA8yBN_Cx1YSP&index=26 at approx. 29 minutes. But it doesn´t. Do you have an idea why? I would really like to leave the port mapping at 8081:4001.

**Comment by aaronzi** [comment]
Hi @Deputy-Chief-Hardy,
this seems to be an issue with the port mapping then. I think I also tried to change the port mappings once and had problems with that. I don't know how the Docker infrastructure is configured in the java examples. I will add @FrankSchnicke to this issue. Maybe he has an idea what causes the problem.

**Comment by FrankSchnicke** [comment]
I will take a look at this and come back to you this week.

**Comment by FrankSchnicke** [comment]
If you change the external port of the AAS Server, the automatically registered AAS/Submodels are still registered with the internal port of the AAS Server. Thus, the UI tries to query the wrong port. This can be fixed via adding 

        - basyxaas_registry_host=http://localhost:8081/aasServer/

To the AASServer container environment. For full documentation of this feature, see https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_AAS_Server_/_Features_/_Registry_Integration#Feature_Configuration

**Comment by Deputy-Chief-Hardy** [comment]
Thanks a lot, it worked! I encountered the error: In an older aas.properties the naming was `registry.hostpath="..."` instead of `registry.host="..."`. That was the problem.
