### ISSUE TITLE
AAS GUI Feature Request:  Borderless / Embedded Visualization Display

### ISSUE THREAD

**Issue by pjaydev** [eclipse-basyx/basyx-applications#125]
We would like to display data from a specific submodel embedded in another web application. To realize this, we would like to embedd the AAS GUI **Visualization** functionality, since it already provides a simple and elegant way of visualizing the data.

It is really useful that it is already possible to directly open a specific submodel in the AAS GUI by properly setting the related `aas` and `path` URL search parameters.

What would really be even more helpful for our scenario would be an additional URL **flag**, such as `...&embed=true`, which, if set, would cause all page elements to remain hidden, except for the "visualization" component (and maybe a copyright / imprint footer).

I suppose you have other features with higher prio on your roadmap, so I just want to bring it up as a suggestions for future development. Maybe it would not be too hard to implement and could be helpful also for other users or scenarios/showcases.

**Comment by seicke** [comment]
Dear @pjaydev,

I've created a PR regarding your feature request: https://github.com/eclipse-basyx/basyx-applications/pull/127

BR
Sebastian

**Comment by FrankSchnicke** [comment]
The feature will be included in the release coming this week.

**Comment by pjaydev** [comment]
Awesome! Thank you very much.
