### ISSUE TITLE
. bootstrap.sh Befehl evtl. falsch dokumentiert

### ISSUE THREAD

**Issue by konnykny** [eclipse-basyx/basyx-applications#13]
Im Readme ist die Rede vom Befehl `. bootstrap.sh` zur Ausführung der GUI unter z.B. Windows. Er funktioniert bei mir jedoch nur mit der Schreibweise `.\bootstrap.sh` - siehe Screenshot. Ist im Readme ein Schreibfehler? Ansonsten liegt der Fehler bei mir.
![image](https://user-images.githubusercontent.com/104373807/212312673-bb73bf7b-b401-4480-be08-cf7c515e31c9.png)

**Comment by aaronzi** [comment]
Danke für den Hinweis. Das ist abhängig von der Shell/Terminal, welches genutzt wird. Grundsätzlich war die Idee dabei, das Starten eines Dev-Servers zu vereinfachen. Unter Windows funktioniert das meines Wissens nach nur unter der Nutzung von WSL (Windows Subsystem for Linux). Dort würde man dann das Terminal benutzen und nicht die Powershell. Für das Terminal wäre der Befehl so wie er in der Doku steht richtig.

**Comment by aaronzi** [comment]
Als Hinweis am Rande: Es bietet sich an unter Windows auch mit dem Dockerfile zu arbeiten. Wenn der Container erstellt wurde besteht die Möglichkeit sich z.B. in Visual Studio Code auf den Container zu verbinden und von dort zu entwickeln.
