### ISSUE TITLE
demo registry server: http://52.170.212.185:4999 don't work

### ISSUE THREAD

**Issue by MarcoTwice** [eclipse-basyx/basyx-applications#14]
The demo demo registry server: http://52.170.212.185:4999/ don't work. 
Please provide it.

**Comment by aaronzi** [comment]
Hello @MarcoTwice. Could you please provide more information about your issue. As far as I know, there is no publicly hosted Registry Server. You could use the Registry provided in the Backend folder of this repository or alternatively follow this tutorial to setup a basic example using the AAS GUI, AAS Server and a Registry Server: https://wiki.eclipse.org/BaSyx_/_Introductory_Examples
If you just want to start a Registry, you can look at this article: https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_Registry
Hope this helps :)

**Comment by aaronzi** [comment]
Edit to my previous comment: I checked the README again and found the part where it says there is a demo registry which is available publicly. This seems to be not the case anymore. Please follow the suggestions in the message above. I will edit the README and remove the links to the demo.
