### ISSUE TITLE
WebGUI: Generated request contains non standard-conform base64 encodings 

### ISSUE THREAD

**Issue by pjaydev** [eclipse-basyx/basyx-applications#170]
Hello, 

I'm currently working on integrating the AAS Web UI to be used as user interface for our own implemented AAS API.

Our API automatically validates all incoming requests against the official [OpenAPI schema](https://github.com/admin-shell-io/aas-specs-api), before it proceeds with the action, and refuses non schema-conform requests.

I recognized that the request schema validation fails on some requests created by the Web UI on the endpoint `GET
/submodel-descriptors/{submodelIdentifier}` with the error:

```
        {
            "code": "format.openapi.requestValidation",
            "correlationId": "submodelIdentifier",
            "text": "must match format \"byte\"",
            "messageType": "Error",
        }
```

This is based on the fact that the base64 encoded parameter value lack of the padding `=` characters on the end of the generated base64 strings, which are required, if the encoded data length is not a multiple of 4.

In this case, the OpenAPI schema validator (respectively the JSON Schema validator working under the hood) refuses the non standard-conform base64 value and therefore refuses the request, since the parameter schema is defined as:
```yaml
- name: submodelIdentifier
  in: path
  ...
  schema:
    type: string
    format: byte
```

I assume, the problem lies here, in the last replacement: 
https://github.com/eclipse-basyx/basyx-applications/blob/319d484c01f51266cbd4c8eb00bb2a6045492a8a/aas-gui/Frontend/aas-web-gui/src/mixins/SubmodelElementHandling.ts#L55

Instead of replacing the '=' by '', they the should be replaced by `%3D`, which is the URL-conform representation of `=`.

Sorry for being too lazy for not creating a PR myself ;) I do not have the full overview over the codebase, but maybe @aaronzi since you are the main developer, you could also check if this or a similar problem could also lead to problems on other parts of the implementation.

Thanks in advance!

**Comment by aaronzi** [comment]
Good find. Thank you for raising this issue. I will have a look at that.
