### ISSUE TITLE
Add option to download the AASX file with concept descriptions

### ISSUE THREAD

**Issue by mateusmolina-iese** [eclipse-basyx/basyx-applications#171]
**Is your feature request related to a problem? Please describe.**
When downloading the AASX, the concept descriptions are not exported by default.

**Describe the solution you'd like**
An option to choose whether to export the concept descriptions or not.

**Comment by aaronzi** [comment]
This actually seems to be a backend problem (AAS Environment serialization endpoint). The AAS Web UI already has this feature:

https://github.com/eclipse-basyx/basyx-applications/blob/319d484c01f51266cbd4c8eb00bb2a6045492a8a/aas-gui/Frontend/aas-web-gui/src/components/AppNavigation/AASList.vue#L369

**Comment by aaronzi** [comment]
This is now fixed here: https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/320
Feel free to close this issue.
