### ISSUE TITLE
WebUI: Endpoint used for updating MultiLanguageProperty elements 

### ISSUE THREAD

**Issue by pjaydev** [eclipse-basyx/basyx-applications#175]
I'm currently working on integrating the AAS Web UI to be used as user interface for our own AAS API implementation, which fully complies with the 
[OpenAPI schema](https://github.com/admin-shell-io/aas-specs-api).

I realized that for updating values on `Property` typed submodel elements, the WebUI sends a `PATCH` request to: `/submodels/{submodelIdentifier}/submodel-elements/{idShortPath}/$value` - which is the way to go, as far as I understand the spec.

But for updating values on `MultiLanguageProperty` typed submodel elements, the WebUI uses the endpoint:
`PUT` `/submodels/{submodelIdentifier}/submodel-elements/{idShortPath}`. It then sets the updated effective value of this element on the additional `value` object property, which is actually not included in the [official request schema for this endpoint](https://app.swaggerhub.com/apis/Plattform_i40/SubmodelRepositoryServiceSpecification/V3.0.1_SSP-001#/Submodel%20Repository%20API/PutSubmodelElementByPath_SubmodelRepo). 

May I ask what is the reason behind not using the endpoint `PATCH /submodels/.../$value` in this case as well? Could this be adjusted to comply with the OpenAPI spec?

Thank you!

**Comment by aaronzi** [comment]
Thank you for raising this issue.
This is still from the DotAAS V1 era where the $value endpoints did not exist.
I must have forgotten to change this. I will update you once this is fixed.

**Comment by pjaydev** [comment]
Ah, I see! I haven't been dealing with the AAS before v3 :)

Thanks for fixing this!
