### ISSUE TITLE
[BUG] Update of AAS DetailsCard

### ISSUE THREAD

**Issue by seicke** [eclipse-basyx/basyx-applications#177]
**Describe the bug**
AAS DetailsCard is not updated after **selecting** another AAS

**To Reproduce**
1. Open aas-gui (in my case http://localhost:3099/)
2. Selecting an AAS and open the AAS Details Card (click on (i) icon)
3. Selecting another AAS
4. AAS Details Card is not updated with respect to the new selected AAS

**Expected behavior**
If the AAS DetailsCard is shown it will be updated with respect to the current selected AAS

**BaSyx (please complete the following information):**
- BaSyx Version v2.0
- AAS Version DotAAS V3, see example files

**Screenshots to Reproduce**
Step 1: 
![localhost_3099_](https://github.com/eclipse-basyx/basyx-applications/assets/2117267/72de4504-d6c8-4714-99be-bec168d6c6f8)

Step 2:
![localhost_3099_ (1)](https://github.com/eclipse-basyx/basyx-applications/assets/2117267/e08c5342-391f-4866-ba43-6113ffc7e228)

Step 3 + 4:
![localhost_3099_ (2)](https://github.com/eclipse-basyx/basyx-applications/assets/2117267/f089dbfc-ceba-43a4-a827-761898c2f023)

Expected behavior (after step 3):
![localhost_3099_ (3)](https://github.com/eclipse-basyx/basyx-applications/assets/2117267/b9c7620c-03dd-4e18-bdce-6d89dced53c0)

**Used Asset Administration files (.aasx/.json/.xml)**
[AAS examples.zip](https://github.com/user-attachments/files/15929398/AAS.examples.zip)

**BaSyx configuration**
Default configuration of aas-environment, aas-registry, sm-registry, aas-discovery and aas-gui (see [BaSyx Starter Kit](https://basyx.org/#/get-started)) (the latest docker image version)

**Additional context**
I'm not sure if it's a bug, or if it's intentional that the user should click on the (i) icon of an AAS to update the DetailsCard.

Personally, as I said, I would expect the DetailsCard to be updated every time an AAS is selected. 

If this is a bug, I will be happy to provide a PR to fix.

**Comment by seicke** [comment]
*Addition*
**Describe the bug**
AAS DetailsCard is not updated after **jumping** to another AAS (e.g. from the SM BOM plugin)

**To Reproduce**
Steps to reproduce the behavior:
1. Open SM BOM visualization (DetailsCard of selected AAS is shown)
2. Click on Jump Button
3. AAS Details Card is not updated with respect to the new selected AAS

**Screenshots to Reproduce**
Step 1 + 2:
![localhost_3099__aas=http___localhost_9981_shells_aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvYWFzLzkyNDNfMDE5MF80MDQyXzkyNzU path=http___localhost_9981_submodels_aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vNTU0M18wMTkwXzQwNDJfNzU0Nw_submodel-elements_Box PFC20](https://github.com/eclipse-basyx/basyx-applications/assets/2117267/b7f9a52b-a1d8-4fdc-9fe2-3a954b7766f4)

Step 3:
![localhost_3099__aas=http___localhost_9981_shells_aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvYWFzLzkyNDNfMDE5MF80MDQyXzkyNzU path=http___localhost_9981_submodels_aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vNTU0M18wMTkwXzQwNDJfNzU0Nw_submodel-elements_Box P (1)](https://github.com/eclipse-basyx/basyx-applications/assets/2117267/886ef6b6-be2d-4743-b6f1-965e6a0ee54c)

Expected behavior (after step 3):
![localhost_3099__aas=http___localhost_9981_shells_aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvYWFzLzkyNDNfMDE5MF80MDQyXzkyNzU](https://github.com/eclipse-basyx/basyx-applications/assets/2117267/45634c10-3383-4f18-ad4b-74d5683450c1)

**Comment by aaronzi** [comment]
Hi @seicke,

that's definitely a bug. If you like to I would be happy if you provide a PR with a fix for this :)
