### ISSUE TITLE
[BUG] AAS GUI does not work remotely

### ISSUE THREAD

**Issue by lindertho** [eclipse-basyx/basyx-applications#180]
**Summary:**
There seems to be a problem using the AAS GUI remotely. When the setup example is used and accessed locally, it works fine. However, when the GUI is used remotely through a browser, it sometimes uses invalid localhost IPs even if the correct remote IPs are specified. We are unsure if this is an internal error or an issue on our side.

**Steps to Reproduce:**
1. Host the example Docker compose on a remote server.
2. Connect from a local machine.
3. Specify the remote IPs in the endpoints and connect.
4. Try to access one of the AAS.

**Expected Behavior:**
The AAS can be accessed remotely.

**Actual Behavior:**
The AAS cannot be accessed.

**Screenshots**
![image](https://github.com/eclipse-basyx/basyx-applications/assets/50629169/00caaf52-5b69-481b-9186-0e17dac46ec0)

**Version**
eclipsebasyx/aas-gui:v2-240515

**Comment by aaronzi** [comment]
Hello @lindertho,

thank you for raising this issue. The UI caches those endpoint configurations in the local storage of the browser. It could be that an old endpoint is still cached. What you could try is to click on `connect` for all the endpoints. Please inform me if this resolves the problem or not.

**Comment by lindertho** [comment]
Ah, perfect. Thank you for the help. 
Updating the `basyx.externalurl` in the `aas-env.properties` file resolved the issue.
