### ISSUE TITLE
[BUG] Visualization Plugin not working properly for HandoverDocumentation submodel

### ISSUE THREAD

**Issue by barthchristian** [eclipse-basyx/basyx-applications#197]
**Describe the bug**
No file preview available for visualization plugin within the handover documentation submodel
![NoDigitalFileFound](https://github.com/eclipse-basyx/basyx-applications/assets/48819812/02f88a7a-7501-47e0-86b9-7aaf5ac78847)
Despite the pdf file being present in the AAS, it is accessible when brwosing to the DigitalFile01 entity (see 2nd screenshot below) 

**To Reproduce**
1. Download the following AAS: 
[1376426_DSBC-32-100-PPVA-N3_71e7561b-9646-421d-8864-e87320932b84.zip](https://github.com/user-attachments/files/16143617/1376426_DSBC-32-100-PPVA-N3_71e7561b-9646-421d-8864-e87320932b84.zip)
2. Rename extension to .aasx
2. Upload on Basyx-Setup
3. Browse to HandoverDocumentation submodel
4. Go to Document01?BedienungsanleitungDE in the Visualization tab

**Expected behavior**
Show the content of the Bedienungsanleitung PDF, similar to what is shown when browsing to the DigitalFile01 within the submodel (see: 
![DigitalFilePreview](https://github.com/eclipse-basyx/basyx-applications/assets/48819812/4b11cc45-a23c-4668-b004-abd860a0c2d8)
)

**BaSyx (please complete the following information):**
- BaSyx Version  v2.0 
- BaSyx SDK Java
- AAS Version  DotAAS V3

**Screenshots**
see inline

**Used Asset Administration files (.aasx/.json/.xml)**
see inline

**BaSyx configuration**
Downloaded minimal configuration from: http://basyx.org/#/
-> no discovery, no mongodb, no mqtt, no dashboard

**Desktop (please complete the following information):**
 - OS: Ubuntu 24 (virtual machine)
 - Browser firefox
 - Version 124.0.1

**Comment by aaronzi** [comment]
Hi Christian, I will have a look. Thanks a lot for the detailed information. I recently fixed a bug that is definitely related to that. The fix I did there maybe also resolves this issue. I will update you once I know more. If that is the case we will update the image on Dockerhub as soon as possible.

**Comment by aaronzi** [comment]
Found the problem. This is definitely a bug and an oversight on my side. The ContactInformation plugin checks for the PreviewFile and DigitalFile based on the idShort and not the SemanticId as it should have. I will fix this as soon as possible and we will update the Docker image.
