### ISSUE TITLE
UI not synchronized with BaSyx Environment in AWS Cloud infrastructure 

### ISSUE THREAD

**Issue by barthchristian** [eclipse-basyx/basyx-applications#206]
**Describe the bug**
When running a basic BaSyx docker-compose project from BaSyx.org, the following error occrus:
The UI is not properly synchronized with the environment. 
It is not possible to view or edit existing AAS from the UI.
![image](https://github.com/user-attachments/assets/6bd1bdc2-e182-4e01-a5e8-442e252c1d9e)
It is not possible to upload AAS via the UI. (Failed to fetch error, same as below)
Within the General Settings tab the registry endpoints is empty, when trying to manually connect: 
![image](https://github.com/user-attachments/assets/cf388e0f-b187-4320-812b-98f8e3f41d40)

All docker instances run with status healthy. All APIs are working as intended to the best of my knowledge.

**To Reproduce**
1. Create virtual machine on aws. Instance type t3.medium, OS: ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20240701.1
2. Download and run a basic BaSyx.org project (no discovery, no timeseries data, no mqtt, no mongoDB, with UI using standard ports and settings, see attachments)
3. Connect to UI endpoint
4. The APIs of the environment and registry work as intended from all what I can say. It is possible to upload the attached AASX file to the environment via postman. All data seems to be present in the environment, also the registry has the correct settings, as seen e.g., here:
![image](https://github.com/user-attachments/assets/11348db9-4046-4b6d-8b3c-84dbfdd398f4)

**Expected behavior**
UI capable of displaying the data within environment, + upload :)

**BaSyx (please complete the following information):**
- BaSyx Version v2 (from BaSyx.org)
- BaSyx SDK Java
- AAS Version DotAAS V3

**Screenshots**
see inline

**Used Asset Administration files (.aasx/.json/.xml)**
[1376426_DSBC-32-100-PPVA-N3_71e7561b-9646-421d-8864-e87320932b84.zip](https://github.com/user-attachments/files/16246433/1376426_DSBC-32-100-PPVA-N3_71e7561b-9646-421d-8864-e87320932b84.zip)

**BaSyx configuration**
[basyx-setup (2).zip](https://github.com/user-attachments/files/16246437/basyx-setup.2.zip)

**Desktop (please complete the following information):**
 - OS: Ubuntu (virtual instance on AWS)
 - Browser MS Edge
 - Version 125.0.2535.92

**Additional context**

**Comment by barthchristian** [comment]
Additional info after a debug session with Aaron: 
when using the absolute ip addresses as well as the basyx.externalurl entry in the aas-env.properties as explained here: https://github.com/eclipse-basyx/basyx-applications/issues/180#issue-2370923817
The connection is working. However, there is presumably still a bug in the UI for resolving the correct ports of the various remote components. Aaron will work on a fix, thanks!

**Comment by aaronzi** [comment]
The problem was in the configuration of the basyx.externalurl. Instead of `http://localhost:8081` with a `:` between the URL and the port, a `/` was used. This caused the registry integration feature to remove the port from the path, resulting in the problem described above.
