### ISSUE TITLE
Default Font Color in Light Theme

### ISSUE THREAD

**Issue by FischerRene** [eclipse-basyx/basyx-applications#21]
The default font color of the graph visualization is (very close to) white and therefore not visible by default.
It will be changed after switching the themes, but reloading the site defaults back to the bright font color.
(This can be reproduced by using the white theme as a default when accessing the site.)

Here is an example screenshot.
![image](https://user-images.githubusercontent.com/33397768/220880196-628b2591-54b0-44e8-ba63-9a703cc95339.png)

**Comment by FrankSchnicke** [comment]
Fixed with https://github.com/eclipse-basyx/basyx-applications/pull/22
