### ISSUE TITLE
[BUG] basyx.org 'getting started' results in unhealthy aas-env container when adding AAS file

### ISSUE THREAD

**Issue by christianklausML** [eclipse-basyx/basyx-applications#233]
**Describe the bug**
When I use the 'getting started' of basyx.org and add an AAS file, it results in an unhealthy aas-env container when running docker-compose up -d.

**To Reproduce**
1. start 'getting started' with basic properties: only AAS Web UI is activated and a AAS is provided. For example Siemens or FESTO public AAS or my own generated AAS file.
2. run docker-compose up -d
3. See error

**Expected behavior**
Everything healthy. When accesing AAS UI, AAS should be loaded.

**BaSyx (please complete the following information):**
- BaSyx: 'getting started' from basyx.org
- AAS Version: I believe it is DotAAS V3. How can I check? Files can be opened in AASX Package Explorer V3.0

**Screenshots**
![aas-env_unhealthy](https://github.com/user-attachments/assets/37369c37-19e7-405d-a903-1d13ac4d47d9)

**Used Asset Administration files (.aasx/.json/.xml)**
file format not supported. Adding .zip.
[AAS_Files.zip](https://github.com/user-attachments/files/16612539/AAS_Files.zip)

**BaSyx configuration**
Provide details about the configuration you used. If possible, attach the configuration as a .zip file.

**Desktop (please complete the following information):**
 - OS: Windows 11, also tried on Windows 10 and Ubuntu
 - Browser chrome

**Comment by mdanish98** [comment]
Hi @christianklausML 

It looks like you are using an old version of the AASX files which is conformant to the Specification of the AAS version 2. The Specification of the AAS version 2 was supported in BaSyx V1 which is now end of life. The starter kit only provides the basic setup for BaSyx V2 which is compliant with the Specification of the AAS version 3.
Would it be possible for you to check with the AASX files based on the Specification of the AAS version 3?

You may use any of these examples files [Example AASX - BaSyx V2](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples/BaSyxMinimal/aas), both the files are conformant to Specification of the AAS version 3.

**Comment by christianklausML** [comment]
Hi @mdanish98 

Thanks, that helped. How can I check the Version of my AAS file? If I generate it using AASX Package Explorer V3.0 it should automatically be an AAS V3, right?

**Comment by mdanish98** [comment]
HI @christianklausML 

Happy to hear :)
Yes, if you use this [AASX PE](https://github.com/eclipse-aaspe/package-explorer/releases/tag/v2024-05-08.alpha) then it automatically creates the V3 AAS.

You can check [here](https://github.com/eclipse-aaspe/package-explorer/tags) for all the latest releases of AASX Package Explorer.
But the latest version i.e., [v2024-06-10.alpha](https://github.com/eclipse-aaspe/package-explorer/releases/tag/v2024-06-10.alpha) has some issues, so please use the version suggested above (v2024-05-08.alpha).
