### ISSUE TITLE
[BUG] Company Logo not applied

### ISSUE THREAD

**Issue by jannikf02** [eclipse-basyx/basyx-applications#234]
**Describe the bug**
Adding a Company Logo does not work, it is not included after downloading the setup.

**To Reproduce**
1. Upload Company Logo
2. Click Apply
3. Download

**Expected behavior**
Company Logo Applied and included in zip file

**Comment by aaronzi** [comment]
Thank you for the bug report. I deployed a fix for the Starter Kit. Please verify that it solves the problem for you.

**Comment by FriedJannik** [comment]
Edit to the issue:
I was trying to only upload a logo (no Favicon)
This is not working, and no error is thrown

**Comment by aaronzi** [comment]
Fixed, now you can just upload the logo without the need to provide an icon
