### ISSUE TITLE
Default registry configuration

### ISSUE THREAD

**Issue by StenGruener** [eclipse-basyx/basyx-applications#24]
Hi @aaronzi,

thank for your work.

It would be great to add a ?registry query parameter similar to ?aas paremeter in order to be able to set a default registry.

Even better it would be to pass a registry using environmental variables https://stackoverflow.com/questions/50828904/using-environment-variables-with-vue-js.

BR

**Comment by aaronzi** [comment]
Hi @StenGruener,

thank you for your feature-recommendation. This functionality is very useful and already in development.
I will give you an update when it is ready in the next release.

**Comment by aaronzi** [comment]
Hi @StenGruener,

the new version of the AAS Web UI is now available here on GitHub. The Docker Image will follow soon on Dockerhub. The Registry URL can now be configured via environment variables. Please refer to the README (Chapter Docker) for a brief explanation on how to use it.

**Comment by StenGruener** [comment]
Thank you, this worked out very nicely!
