### ISSUE TITLE
[Feature Request] Support for property value type `dateTimeStamp`

### ISSUE THREAD

**Issue by sokotim** [eclipse-basyx/basyx-applications#27]

**Comment by aaronzi** [comment]
Hi @sokotim, that sounds like it could be a helpful feature.
The property field can already display the dateTimeStamp as a string.
You are probably interested in something like a date/time picker.
If not, please provide more details regarding your feature request.

**Comment by sokotim** [comment]
Hi @aaronzi, currently the default is an input field of type `number`. You can only see the current value when the field is selected:

<img width="453" alt="aas-gui-property-dateTimeStamp-input-number" src="https://github.com/eclipse-basyx/basyx-applications/assets/26604186/ca303b4f-39ac-4717-bbcb-1326bad836f6">
<img width="453" alt="aas-gui-property-dateTimeStamp-input-number-click" src="https://github.com/eclipse-basyx/basyx-applications/assets/26604186/370dc888-ce4f-45f2-a244-eef4dc311759">

I agree, just showing the value as a string (input type `text`) would already be helpful. A date/time picker is maybe not that straightforward to implement because you have to find a way to deal with the timezone.

**Comment by aaronzi** [comment]
Thank you for pointing that out. That seems like an issue to me. But fixing it could also be an opportunity for a dedicated visualization of dateTimeStamps. Could you please provide an AASX-File for me as an example? That would save me some time.

**Comment by sokotim** [comment]
Here you are: [timestamp.zip](https://github.com/eclipse-basyx/basyx-applications/files/11531127/timestamp.zip)
