### ISSUE TITLE
[Feature Request] Support for submodel element Blob

### ISSUE THREAD

**Issue by sokotim** [eclipse-basyx/basyx-applications#28]
Blob submodel elements currently only show a warning that this element type is not supported.

We have a use case where our submodel contains a base64 encrypted blob with mimetype `img/jpg`. It would be very nice to display this data as an image like a submodel element of type File with the same mime type.

**Comment by aaronzi** [comment]
Yes, you are right. Blobs are currently not supported. I will add them to the feature list for the next patch. I will give you an update here when this is implemented.
