### ISSUE TITLE
eclipsebasyx/aas-gui not working behind nginx with path like /aasui/

### ISSUE THREAD

**Issue by DavidWeissIFM** [eclipse-basyx/basyx-applications#34]
Hi, I have a small problem that the AAS GUI does not work behind a nginx with path like https://127.0.0.1/aasui/.

Unfortunately I can't directly use the publish port and have to route it behind a nginx configured path.
However, the container can not handle it at the moment.
As you can see in the response, all paths (from **"/@vite/client"** and **"/src/main.ts"**) are absolute.
So the browser can't find them because the **/aasui/** path is missing.

Is there any way to configure the docker container to work behind a path?

Thanks for your help.

**docker-compose**:
```
version: "3"
services:
  aasui:
    image: eclipsebasyx/aas-gui:v230403
    container_name: aasui
    restart: always
    ports:
      - "3000:3000"
```

**nginx**:
```
listen 80 default_server;
listen [::]:80 default_server;

sendfile                        on;
gzip                            on;

large_client_header_buffers 8 64k;

-----

location = /aasui {
    return 302 /aasui/;
}

location /aasui/ {
    proxy_pass          http://127.0.0.1:3000/;
    proxy_set_header X-Base-Path /aasui;
    include             proxy.conf;
}
```
	
**proxy.conf**:
```
proxy_buffers                           32 4m;
proxy_busy_buffers_size         25m;
proxy_buffer_size                       512k;
proxy_ignore_headers            "Cache-Control" "Expires";
proxy_max_temp_file_size        0;
proxy_set_header                        X-Real-IP $remote_addr;
proxy_set_header                        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header                        Host $http_host;
proxy_set_header                        Origin $request_uri;
client_max_body_size        1024m;
client_body_buffer_size     4m;
proxy_connect_timeout           600;
proxy_read_timeout                      600;
proxy_send_timeout                      600;
proxy_intercept_errors          off;

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
```

**request**:
![image](https://github.com/eclipse-basyx/basyx-applications/assets/90178153/7df3bb67-b954-43a9-8d10-07ff06b2df67)

**response**:
```
<!DOCTYPE html>
<html lang="en">

<head>
  <script type="module" src="/@vite/client"></script>

    <meta charset="UTF-8" />
    <link rel="icon" href="./src/assets/Logo/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AAS UI</title>
</head>

<body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
</body>

</html>
```

**Comment by aaronzi** [comment]
Hi @DavidWeissIFM,

I am not quite sure if I fully understand your issue. Your use case is definitely relevant as far as I can evaluate what you are trying to do with Nginx and the UI. If you want, we could discuss this separately (maybe even in an online meeting). Please write me a mail (aaron@zielstorff.com). Gladly also in German, I see you are from IFM in Germany.

**Comment by StenGruener** [comment]
Hi +1 on this, all kinds or substitutions in nginx also did not help - i have given up after 30 mins

Our problem is that we want to run the aas-gui behind a reverse proxy e.g. localhost/aasui/, but the app itself is not aware of it, since it runs on its own webserver. Maybe this does help? https://medium.com/h-lab/how-to-deploy-vue-with-nginx-on-sub-path-ed8eadbc1bc5

module.exports = {
  publicPath: process.env.APP_BASE_PATH
}

@DavidWeissIFM  not sure, haven't tried yet

**Comment by aaronzi** [comment]
I am currently taking a look into that. @StenGruener thank you for the suggestion. This could possibly be a way to avoid rewriting the routing of the entire web app. Seems like this wasn't considered a use case for vue out of the box and I also did not take a look into that when I began implementing the UI. In the next update, however, deploying the application to subpaths via nginx will be possible as requested. ETA should be the beginning of October.

**Comment by StenGruener** [comment]
woow @aaronzi thats a long yourney... will try to implement and build my image manually

**Comment by StenGruener** [comment]
So almost everything worked except
`proxy_pass http://aasui:3000;`
needs to be
`proxy_pass http://aasui:3000/aasui/;`

I did not test proxy.conf though since it looks like I do not need ws forwarding for now (i use basyx java as backend), do i need ws forwarding?
