### ISSUE TITLE
File MIME types not working

### ISSUE THREAD

**Issue by mm-mse** [eclipse-basyx/basyx-applications#38]
The MIME-types (contentType) of files are not read from AAS Metamodel v3 and images are therefore not displayed

**Comment by aaronzi** [comment]
I will take a look into that ;)

**Comment by aaronzi** [comment]
Problem resulting from a name change. **mimeType** is now called **contentType**. The fix will be in the next update. Thanks for pointing this out :)

**Comment by aaronzi** [comment]
I fixed the problem. Update coming next week. I also implemented a feature to display defaultThumbnails of assets. Both image files as well as asset thumbnails currently only support external links. The BaSyx AAS- and Submodel- Repository will feature dedicated endpoints for this in the future.

Here is a little sneak peek:

![image](https://github.com/eclipse-basyx/basyx-applications/assets/17433117/7f161858-405f-46e7-a594-79c524865246)
