### ISSUE TITLE
RBAC integration for AAS-GUI

### ISSUE THREAD

**Issue by abhishekmaha23** [eclipse-basyx/basyx-applications#66]
The RBAC in Basyx v2 is being developed currently, and is a pretty cool feature - thus I'm creating an issue here to track the client-side of the OpenID + OAuth2 side of the Basyx-GUI.

**Comment by abhishekmaha23** [comment]
Related issues so far:
- https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/159
- https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/180
- https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/186
I'm working on additional Keycloak deployment Helm configurations for Kubernetes, and so I'm looking forward to helping develop the client parts if needed!

**Comment by aaronzi** [comment]
Thank you for opening this issue @abhishekmaha23.
I will start to implement this feature once all Repositories support RBAC. I'm not exactly sure when this will be and what my schedule will look like then. Therefore thank you for offering your help :) If you are planning to develop some client parts, please notify me. I would be happy to share some tasks with you regarding the BaSyx AAS GUI.

**Comment by rosseboe** [comment]
We brought up this topic in the BaSyx Open Hour June 7th, where our ask is to have native support for Microsoft Entra ID.  Should I create a separate issue for this?

**Comment by aaronzi** [comment]
Hi @rosseboe,

yes, please create a separate issue here: https://github.com/eclipse-basyx/basyx-java-server-sdk/issues

**Comment by rosseboe** [comment]
thanks @aaronzi . I have created issue #163
