### ISSUE TITLE
Opening Submodel: Stuck with spinner

### ISSUE THREAD

**Issue by adankert70** [eclipse-basyx/basyx-applications#9]
Connecting to Basyx registry works as expected, the shells are listed.
When clicking on a shell a spinner appears in the submodels column, but it is stuck there for all eternity. No result is produced. I cannot find any problems in logs, neither in GUI nor in registry,

**Comment by aaronzi** [comment]
Can you please provide more information about the shells which were registered in the Registry. Do they have their own Rest interface or are they only available "offline"? Which Basyx SDK were you using? Another reason for the occurrence of the issue can be multi-AAS from an AAS-repository. Those are currently not supported.

In addition to that, the stuck spinner is fixed in the newest Pull request. If a shell can't be reached a timeout will occur after a short time.

**Comment by adankert70** [comment]
Thank you for the response. I have 4 example AAS in a Basyx repository. I guess that is my problem then. Will re-test with only one.

**Comment by adankert70** [comment]
Update: Stuck with spinner when there is only one AAS in the Basyx registry as well.
I am running Basyx aas server and registry Docker containers. Registry and servers are backed by MongoDB databases.

**Comment by aaronzi** [comment]
Can you access said AAS through your browser by entering it's URL? Is the port of the Docker container exposed to be accessed from outside the container?

**Comment by aaronzi** [comment]
I think I found the issue and it seems to have to do with AAS repositories in general. I tested this with the dotnet sdk `MultiAssetAdministrationShell` example and `ComplexAssetAdministrationShellScenario`. When I try to retrieve the shell(s) I get this response:

![image](https://user-images.githubusercontent.com/17433117/196385877-cbdc3605-c902-4f6d-8cc1-e22375d50128.png)

I will try to fix the code in the examples of the Dotnet SDK and try again if the GUI works.

But I definitely think the GUI is not the issue. In the meantime you could try to use AAS which are directly registered in the registry and not part of an AAS repository.

**Comment by adankert70** [comment]
Thank you for all your guidance. I think I see the problem on my side. Probably some bad config inside my container(s). It uses localhost:4001 addresses for the endoints:
![image](https://user-images.githubusercontent.com/56963150/196447056-4d21af0f-eb83-41b9-8817-ac7ce0851b0d.png)
If the GUI reads those endpoints and try to access them it will fail of course!
I will try to find the correct parameters and update.

**Comment by aaronzi** [comment]
You are welcome :) Hopefully you can fix the problem and use the GUI afterwards.

**Comment by Huang2Ning** [comment]
Hello, I encountered the same problem when showing submodel details in GUI. I can access my AAS server, see this AAS well registered in the registry server and see this AAS appearing in GUI. However, the submodel information doesn't appear in GUI. I would like to ask how did you solve this spinning problem? Thank you in advance.
![image](https://user-images.githubusercontent.com/33783614/203420550-64201ed3-a7e3-4f05-be4e-98d518985d81.png)

![image](https://user-images.githubusercontent.com/33783614/203420703-afc77c6f-310f-45dc-bb13-e633ec9f3361.png)

![image](https://user-images.githubusercontent.com/33783614/203420798-2e03d2b6-7961-4e23-aa8c-67d9b9a0f8f6.png)

**Comment by aaronzi** [comment]
This seems to be an issue related to the configuration of the registry. First of all, is there a reason you access the registry this way **127.0.0.1:8082/registry** instead of this way **127.0.0.1:8082**? I think that's the proposed way to do it but I will definitely test your implementation to check if that could be the reason for the problem.

Just for your information how the GUI works: It takes the first endpoint address and tries to reach the Asset Administration shell with that URL. You could try to copy that exact address and open it in another tab. If that works the GUI should work to.

Hope that helps :)

**Comment by Huang2Ning** [comment]
Thank you for your response. I tried with different endpoints but it still not work. Even when I followed exactly the steps shows in this tutorial, I couldn't access to the submodel information by GUI.
https://wiki.eclipse.org/BaSyx_/_Introductory_Examples_/_Java_/_Step_5

**Comment by aaronzi** [comment]
Please also check the request send from your browser (press F12 then open network tab).

A screenshot like this would also be helpful:

![image](https://user-images.githubusercontent.com/17433117/203522560-895c15b1-4303-4a20-a3a4-8e3350def5a0.png)

**Comment by Huang2Ning** [comment]
Here's the screenshot that connnect to the registry (work)
![image](https://user-images.githubusercontent.com/33783614/203527584-f8ff980c-e34f-4923-a4dc-cc517c5ace76.png)
Screenshot of discovering submodels (not work)
![image](https://user-images.githubusercontent.com/33783614/203527750-37690c2f-5ef1-4a35-bc41-1d52564b484c.png)
I used the registry server and gui server from docker, and the /registry/ui is not working from my side.

**Comment by Huang2Ning** [comment]
Thank you for your help, I added a CROS plugin in my navigator and it works! :)

![image](https://user-images.githubusercontent.com/33783614/203530646-8278b8bb-3a8f-4987-afd3-c3354a5947fd.png)

**Comment by aaronzi** [comment]
Oh well. CORS was the Problem... That's annoying. I thought CORS would not affect the localhost. This is getting more restrictive every month I feel.

**Comment by FrankSchnicke** [comment]
We added the possibility to configure CORS in the last release of BaSyx. You can configure it in the context.properties as described [here](https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_Context).

**Comment by Deputy-Chief-Hardy** [comment]
Hi, unfortunately I have the same problem with the never ending spinning wheel. In the context.properties of server and registry it says `accessControlAllowOrigin=*`.

Here is a screenshot. 
![Screenshot GUI](https://user-images.githubusercontent.com/49750085/211302306-4446bd0f-8bfe-446d-b77f-006729a3a7d1.PNG)

Do you have any idea how to proceed?
